In [5]:
import sys
import pandas as pd
import numpy as np

in_file = 'historydata.xlsx'

print ("program start!")
df = pd.read_excel(in_file,dtype='unicode')
print ("end!")

program start!
end!

In [11]:
cols = df.columns.drop(['DATE','CODE','NAME'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [12]:
df

,DATE,CODE,NAME,PRC,ADJ_PRC,SHRS,IDX_APT_SHRS,COM_MRK_VAL_CHG,FIX_MRK_VAL
0,20150102,000070,삼양홀딩스,89800,89800,8564271,8564271,0,0
1,20150102,000140,하이트진로홀딩스,11950,11950,23206765,23206765,0,0
2,20150102,000240,한국테크놀로지그룹,24550,24550,93020173,93020173,0,0
3,20150102,000640,동아쏘시오홀딩스,120000,120000,4481591,4481591,0,0
4,20150102,001040,CJ,157500,148517,29084427,29084427,0,0
5,20150102,001630,종근당홀딩스,60500,60500,3640950,3640950,0,0
6,20150102,001800,오리온홀딩스,1000000,49122,5974969,5974969,0,0
7,20150102,001940,KISCO홀딩스,49200,9860,3695276,3695276,0,0
8,20150102,002020,코오롱,22450,22450,12061185,12061185,0,0
9,20150102,002030,아세아,152000,152000,2191024,2191024,0,0
10,20150102,002250,알보젠코리아,13300,13300,11857922,11857922,0,0
11,20150102,002790,아모레G,1025000,102264,79790980,7979098,0,0
12,20150102,003090,대웅,44250,8877,11628396,11628396,0,0
13,20150102,003300,한일홀딩스,157000,98576,7545313,7545313,0,0
14,20150102,003550,LG,61900,61900,172557131,172557131,0,0
15,20150102,004150,한솔홀딩스,10650,6409,43624470,43624470,0,0
16,20150102,004800,효성,67100,39709,35117455,35117455,0,0
17,20150102,004840,DRB동일,12350,11206,17500000,18010000,0,0
18,20150102,004990,롯데지주,1770000,68295,1421400,1421400,0,0
19,20150102,005720,넥센,86300,8630,5088017,5088017,0,0
20,20150102,005740,크라운해태홀딩스,186500,9971,1473524,1473524,0,0
21,20150102,005810,풍산홀딩스,43300,43300,7835167,7835167,0,0
22,20150102,005990,매일홀딩스,36450,18056,13400000,13400000,0,0
23,20150102,006120,SK디스커버리,64400,38743,20843047,20843047,0,0
24,20150102,006260,LS,53900,53900,32200000,32200000,0,0
25,20150102,006840,AK홀딩스,85100,85100,13247561,13247561,0,0
26,20150102,007860,서연,12300,12300,12387416,12387416,0,0
27,20150102,008930,한미사이언스,15200,13271,54554979,57185523,0,0
28,20150102,009540,한국조선해양,112000,101741,76000000,76000000,0,0
29,20150102,009970,영원무역홀딩스,92200,92200,13635592,13635592,0,0
...,...,...,...,...,...,...,...,...,...
85835,20200402,030530,원익홀딩스,3510,3510,77237981,77237981,0,0
85836,20200402,034310,NICE,18000,18000,37882300,37882300,0,0
85837,20200402,034730,SK,165000,165000,70360297,70360297,0,0
85838,20200402,035080,인터파크홀딩스,1720,1720,58500000,58500000,0,0
85839,20200402,036420,제이콘텐트리,28300,28300,16385071,16385071,0,0
85840,20200402,036530,S&T홀딩스,12700,12700,16303886,16303886,0,0
85841,20200402,038500,삼표시멘트,2465,2465,107357173,107357173,0,0
85842,20200402,040350,큐로컴,2615,2615,113758041,113758041,0,0
85843,20200402,044820,코스맥스비티아이,11550,11550,9603921,9603921,0,0
85844,20200402,057050,현대홈쇼핑,58400,58400,12000000,12000000,0,0
85845,20200402,058650,세아홀딩스,53300,53300,4000000,4000000,0,0
85846,20200402,060980,한라홀딩스,27700,27700,10472070,10472070,0,0
85847,20200402,063080,게임빌,19850,19850,6595192,6595192,0,0
85848,20200402,072710,농심홀딩스,72100,72100,4637790,4637790,0,0
85849,20200402,077360,덕산하이메탈,4820,4820,22718501,22718501,0,0
85850,20200402,078930,GS,38450,38450,92915378,92915378,0,0
85851,20200402,084110,휴온스글로벌,25450,25450,10921362,11464127,0,0
85852,20200402,084690,대상홀딩스,5350,5350,36212538,36212538,0,0
85853,20200402,096760,JW홀딩스,4665,4665,66452155,66452155,0,0
85854,20200402,096770,SK이노베이션,90400,90400,92465564,92465564,0,0
85855,20200402,101060,SBS미디어홀딩스,1795,1795,139896190,139896190,0,0
85856,20200402,102260,동성코퍼레이션,3005,3005,45444970,45444970,0,0
85857,20200402,108790,인터파크,4110,4110,33155480,33155480,0,0
85858,20200402,121440,골프존뉴딘홀딩스,2180,2180,42836818,42836818,0,0
85859,20200402,126560,현대에이치씨엔,3310,3310,112876596,112876596,0,0
85860,20200402,180640,한진칼,72400,72400,59170458,59170458,0,0
85861,20200402,192400,쿠쿠홀딩스,76000,76000,7112437,7112437,0,0
85862,20200402,207940,삼성바이오로직스,464500,464500,66165000,66165000,0,0
85863,20200402,226320,잇츠한불,10700,10700,21929315,21929315,0,0
85864,20200402,267250,현대중공업지주,207500,207500,16286617,16286617,0,0